main: com.zinno.nim.Main
version: 1.2.1
name: DrNIM
author: Zinno
description: Entertaining, lightweight minigame plugin

commands:
  nim:
    description: Get info about NIM
    usage: /NIM
    permission: nim.nim

permissions:
  nim.*:
    description: Access to all NIM commands
    children:
      nim.nim: true
      nim.start: true
  nim.nim:
    description: Use NIM
    default: true
  nim.start:
    description: Start NIM games
    default: true
    children:
      nim.nim: true
  nim.help:
    description: View a list of commands
    default: true
    children:
      nim.nim: true
  nim.debug:
    description: Administrative debug warnings
    default: false
    children:
      nim.nim: true